version: "3"

services:
  nodeosd:
    build: nodeos
    hostname: nodeosd
    container_name: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
      - 8080:8080
    expose:
      - "8888"
      - "8080"
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  chronicle:
    container_name: chronicle
    build: chronicle-docker
    depends_on:
      - nodeosd
    
  keosd:
    container_name: keosd
    image: softwaremill/eos
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8900 --http-alias=keosd:8900 --http-alias=localhost:8900  --plugin  eosio::wallet_plugin --plugin  eosio::wallet_api_plugin --http-validate-host=false --verbose-http-errors
    hostname: keosd
    expose:
      - "8900"
    ports:
      - 8900:8900
    links:
      - nodeosd
    volumes:
      - ./keosd-data:/opt/eosio/bin/data-dir
    stop_grace_period: 10m
